apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: testwithconfig-setp16-gitops
  description: This is GitOps manifest for testwithconfig-setp16   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: testwithconfig-setp16
    janus-idp.io/tekton: testwithconfig-setp16 
    backstage.io/kubernetes-id: testwithconfig-setp16 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:testwithconfig-setp16
