---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: testwithconfig-setp16
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: testwithconfig-setp16 
  name: testwithconfig-setp16
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi