apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: testwithconfig-setp16
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: testwithconfig-setp16 
  name: testwithconfig-setp16
spec:
  ports:
  - port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app.kubernetes.io/instance: testwithconfig-setp16 
